apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-path
  namespace: demo-proto-ns
spec:
  ingressClassName: nginx
  rules:
    - host: localhost
    - http:
        paths:
          - pathType: Prefix
            path: /testAPI
            backend:
              service:
                name: demo-proto-service-clusterip
                port:
                  number: 8081
          - pathType: Prefix
            path: /goAPI
            backend:
              service:
                name: demo-go-service-clusterip
                port:
                  number: 8081